#
# WARNING!
#
# Node Pool is still an experimental feature.
#
# Experimental features will change in backward-incompatible ways.
# Though it would be just a matter of re-creating node pools in case of breaking changes,
# we at least assume you well understand common VPC, KMS, EC2, ELB, CloudFormation, etc. gotchas.
#
# Please use this feature at your own risk.

# Unique name of the node pool. In order to deploy
# more than one node pool into the same AWS account, this
# name must not conflict with an existing cluster.
nodePoolName: {{.NodePoolName}}

# The name of an existing Kubernetes cluster
# Required in order to import reused resources' IDs and ARNs from the cluster
# to this node pool in the CloudFormation layer using Cross Stack References.
clusterName: {{.ClusterName}}

# DNS name routable to the Kubernetes controller nodes
# from worker nodes and external clients. Configure the options
# below if you'd like kube-aws to create a Route53 record sets/hosted zones
# for you.  Otherwise the deployer is responsible for making this name routable
externalDNSName: {{.ExternalDNSName}}

# CoreOS release channel to use. Currently supported options: alpha, beta, stable
# See coreos.com/releases for more information
releaseChannel: {{.ReleaseChannel}}

# The AMI ID of CoreOS.
# If omitted, the latest AMI for the releaseChannel is used.
amiId: {{.AmiId}}

# Name of the SSH keypair already loaded into the AWS
# account being used to deploy this cluster.
keyName: {{.KeyName}}

# Region to provision Kubernetes cluster
region: {{.Region}}

# Availability Zone to provision Kubernetes cluster when placing nodes in a single availability zone (not highly-available) Comment out for multi availability zone setting and use the below `subnets` section instead.
availabilityZone: {{.AvailabilityZone}}

# ARN of the KMS key used to encrypt TLS assets.
kmsKeyArn: "{{.KMSKeyARN}}"

# Number of worker nodes to create, for more control use `worker.autoScalingGroup` and do not use this setting
#workerCount: 1

# Instance type for worker nodes
#workerInstanceType: t2.medium

# Disk size (GiB) for worker nodes
#workerRootVolumeSize: 30

# Disk type for worker node (one of standard, io1, or gp2)
#workerRootVolumeType: gp2

# Number of I/O operations per second (IOPS) that the worker node disk supports. Leave blank if workerRootVolumeType is not io1
#workerRootVolumeIOPS: 0

# Price (Dollars) to bid for spot instances. Omit for on-demand instances.
# workerSpotPrice: "0.05"

# Existing "glue" security groups attached to worker nodes which are typically used to allow access from worker nodes to services running on an existing infrastructure
# workerSecurityGroupIds:
#   - sg-1234abcd
#   - sg-5678efab

# Tenancy of the worker nodes. Options are "default" and "dedicated"
# Documentation: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html
# workerTenancy: default

# Experimental worker config which can be changed in backward-incompatible ways
# worker:
#   # Auto Scaling Group definition for workers. If only `workerCount` is specified, min and max will be the set to that value and `rollingUpdateMinInstancesInService` will be one less.
#   autoScalingGroup:
#     minSize: 1
#     maxSize: 3
#     rollingUpdateMinInstancesInService: 2
#   # Tag the cloudformation stack with the key `kube-aws:cluster-autoscaler:scale-specs` with the value containing
#   # source of truth for cluster-autoscaler to update their autoscaling target and its min/max size.
#   # Currently, enabling this configuration doesn't automatically deploy cluster-autoscaler itself.
#   # Please read [the original issue](https://github.com/coreos/kube-aws/issues/148) carefully for more information.
#   clusterAutoscaler:
#     minSize: 1
#     maxSize: 3
#  # Spot fleet config for worker nodes
#  spotFleet:
#    # Total desired number of units to maintain
#    # An unit is chosen by you and can be a vCPU, specific amount of memory, size of instance store, etc., according to your requirement.
#    # Omit or put zero to disable the spot fleet support and use an autoscaling group to manage nodes.
#    #targetCapacity: 10
#
#    # IAM role to grant the Spot fleet permission to bid on, launch, and terminate instances on your behalf
#    # See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-prerequisites
#    #
#    # Defaults to "arn:aws:iam::youraccountid:role/aws-ec2-spot-fleet-role" assuming you've arrived "Spot Requests" in EC2 Dashboard
#    # hence the role is automatically created for you
#    #iamFleetRoleArn: "arn:aws:iam::youraccountid:role/kube-aws-doesnt-create-this-for-you"
#
#    # Price per unit hour = Price per instance hour / num of weighted capacity for the instance
#    # Defaults to "0.06"
#    #spotPrice: 0.06
#
#    # Disk size (GiB) per unit
#    # Disk size for each launch specification defaults to unitRootVolumeSize * weightedCapacity
#    #unitRootVolumeSize: 30
#
#    # Disk type for worker node (one of standard, io1, or gp2)
#    # Can be overridden in each launch specification
#    #rootVolumeType: gp2
#
#    # Number of I/O operations per second (IOPS) per unit. Leave blank if rootVolumeType is not io1
#    # IOPS for each launch specification defaults to unitRootVolumeIOPS * weightedCapacity
#    #unitRootVolumeIOPS: 0
#
#    launchSpecifications:
#    - # Number of units provided by an EC2 instance of the instanceType.
#      weightedCapacity: 1
#      instanceType: t2.medium
#
#      # Price per unit hour = Price per instance hour / num of weighted capacity for the instance
#      #spotPrice:
#
#      # Defaults to worker.spotFleet.rootVolumeType if omitted
#      #rootVolumeType:
#
#      # Defaults to worker.spotFleet.unitRootVolumeSize * weightedCapacity if omitted
#      #rootVolumeSize:
#
#      # Number of provisioned IOPS when rootVlumeType is io1
#      # Must be within the range between 100 and 2000
#      # Defaults to worker.spotFleet.unitRootVolumeIOPS * weightedCapacity if omitted
#      #rootVolumeIOPS:
#    - weightedCapacity: 2
#      instanceType: m3.large
#    - weightedCapacity: 2
#      instanceType: m4.large

## Networking config

# ID of existing VPC to create subnet in. Leave blank to import the value from the base cluster
vpcId: "{{.VPCID}}"

# ID of existing route table in existing VPC to attach subnet to. Leave blank to import the value from the base cluster
routeTableId: "{{.RouteTableID}}"

# CIDR for Kubernetes VPC. If vpcId is specified, must match the CIDR of existing vpc.
vpcCIDR: "{{.VPCCIDR}}"

# CIDR for Kubernetes subnet when placing nodes in a single availability zone (not highly-available) Leave commented out for multi availability zone setting and use the below `subnets` section instead.
# instanceCIDR: "10.0.0.0/24"

# Kubernetes subnets with their CIDRs and availability zones. Differentiating availability zone for 2 or more subnets result in high-availability (failures of a single availability zone won't result in immediate downtimes)
# subnets:
#   - availabilityZone: us-west-1a
#     instanceCIDR: "10.0.0.0/24"
#   - availabilityZone: us-west-1b
#     instanceCIDR: "10.0.1.0/24"

etcdEndpoints: "{{.EtcdEndpoints}}"

# Required by kubelet to locate the cluster-internal dns hosted on controller nodes in the base cluster
dnsServiceIP: "{{.DNSServiceIP}}"

# Uncomment to provision nodes without a public IP. This assumes your VPC route table is setup to route to the internet via a NAT gateway.
# If you did not set vpcId and routeTableId the cluster will not bootstrap.
# mapPublicIPs: false

# Version of hyperkube image to use. This is the tag for the hyperkube image repository.
# kubernetesVersion: v1.4.5_coreos.0

# Hyperkube image repository to use.
# hyperkubeImageRepo: quay.io/coreos/hyperkube

# Use Calico for network policy.
useCalico: {{.UseCalico}}

# Create MountTargets for a pre-existing Elastic File System (Amazon EFS). Enter the resource id, eg "fs-47a2c22e"
# This is a NFS share that will be available across the entire cluster through a hostPath volume on the "/efs" mountpoint
#
# You can create a new EFS volume using the CLI:
# $ aws efs create-file-system --creation-token $(uuidgen)
#elasticFileSystemId: fs-47a2c22e

# Determines the container runtime for kubernetes to use. Accepts 'docker' or 'rkt'.
# containerRuntime: docker

# Experimental features will change in backward-incompatible ways
# experimental:
#   awsEnvironment:
#     enabled: true
#     environment:
#       CFNSTACK: '{ "Ref" : "AWS::StackId" }'
#   awsNodeLabels:
#     enabled: true
#   loadBalancer:
#     enabled: true
#     names: [ "manuallymanagedelb" ]
#     securityGroupIds: [ "sg-87654321" ]
#   nodeDrainer:
#     enabled: true
#   nodeLabels:
#     kube-aws.coreos.com/role: worker
#   waitSignal:
#     enabled: true

# AWS Tags for cloudformation stack resources
#stackTags:
#  Name: "Kubernetes"
#  Environment: "Production"
