dist: bionic
language: go
go:
  - 1.13.x

script:
  - travis_wait 50 make test-with-cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: ci/publish-docs-as-bot.sh
  on:
    branch: master
