# Unique name of Kubernetes cluster. In order to deploy
# more than one cluster into the same AWS account, this
# name must not conflict with an existing cluster.
clusterName: {{.ClusterName}}

# DNS name routable to the Kubernetes controller nodes
# from worker nodes and external clients. Configure the options
# below if you'd like kube-aws to create a Route53 record sets/hosted zones
# for you.  Otherwise the deployer is responsible for making this name routable
externalDNSName: {{.ExternalDNSName}}

# CoreOS release channel to use. Currently supported options: alpha, beta, stable
# See coreos.com/releases for more information
#releaseChannel: stable

# The AMI ID of CoreOS.
# If omitted, the latest AMI for the releaseChannel is used.
#amiId: ""

# Set to true if you want kube-aws to create a Route53 Alias Record pointing to the controller ELB for you.
#createRecordSet: false

# TTL in seconds for the Route53 RecordSet created if createRecordSet is set to true.
#recordSetTTL: 300

# DEPRECATED: use hostedZoneId instead
# The name of the hosted zone to add the externalDNSName to,
# E.g: "google.com".  This needs to already exist, kube-aws will not create
# it for you.
#hostedZone: ""

# The ID of hosted zone to add the externalDNSName to.
# Either specify hostedZoneId or hostedZone, but not both
#hostedZoneId: ""

# Name of the SSH keypair already loaded into the AWS
# account being used to deploy this cluster.
keyName: {{.KeyName}}

# Additional keys to preload on the coreos account (keep this to a minimum)
# sshAuthorizedKeys:
# - "ssh-rsa AAAAEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEYEXAMPLEKEY example@example.org"

# Region to provision Kubernetes cluster
region: {{.Region}}

# Availability Zone to provision Kubernetes cluster when placing nodes in a single availability zone (not highly-available) Comment out for multi availability zone setting and use the below `subnets` section instead.
availabilityZone: {{.AvailabilityZone}}

# ARN of the KMS key used to encrypt TLS assets.
kmsKeyArn: "{{.KMSKeyARN}}"

# Number of controller nodes to create, for more control use `controller.autoScalingGroup` and do not use this setting
#controllerCount: 1

#controller:
#  # Auto Scaling Group definition for controllers. If only `controllerCount` is specified, min and max will be the set to that value and `rollingUpdateMinInstancesInService` will be one less.
#  autoScalingGroup:
#    minSize: 1
#    maxSize: 3
#    rollingUpdateMinInstancesInService: 2
#  subnets:
#    - availabilityZone: us-west-1a
#      instanceCIDR: "10.0.4.0/24"
#    - availabilityZone: us-west-1b
#      instanceCIDR: "10.0.5.0/24"

# Set to true to put the ELB on the public subnet although having controller nodes on private subnets
#controllerLoadBalancerPrivate: false

# Maximum time to wait for controller creation
#controllerCreateTimeout: PT15M

# Instance type for controller node.
# CAUTION: Don't use t2.micro or the cluster won't work. See https://github.com/kubernetes/kubernetes/issues/18975
#controllerInstanceType: t2.medium

# Disk size (GiB) for controller node
#controllerRootVolumeSize: 30

# Disk type for controller node (one of standard, io1, or gp2)
#controllerRootVolumeType: gp2

# Number of I/O operations per second (IOPS) that the controller node disk supports. Leave blank if controllerRootVolumeType is not io1
#controllerRootVolumeIOPS: 0

# Number of worker nodes to create, for more control use `worker.autoScalingGroup` and do not use this setting
#workerCount: 1

#worker:
#  # Auto Scaling Group definition for workers. If only `workerCount` is specified, min and max will be the set to that value and `rollingUpdateMinInstancesInService` will be one less.
#  autoScalingGroup:
#    minSize: 1
#    maxSize: 3
#    rollingUpdateMinInstancesInService: 2
#  subnets:
#    - availabilityZone: us-west-1a
#      instanceCIDR: "10.0.6.0/24"
#    - availabilityZone: us-west-1b
#      instanceCIDR: "10.0.7.0/24"

# Setting worker topology private ensures NAT Gateways are created for use in node pools.
#workerTopologyPrivate: false

# Maximum time to wait for worker creation
#workerCreateTimeout: PT15M

# Instance type for worker nodes
# CAUTION: Don't use t2.micro or the cluster won't work. See https://github.com/kubernetes/kubernetes/issues/16122
#workerInstanceType: t2.medium

# Disk size (GiB) for worker nodes
#workerRootVolumeSize: 30

# Disk type for worker node (one of standard, io1, or gp2)
#workerRootVolumeType: gp2

# Number of I/O operations per second (IOPS) that the worker node disk supports. Leave blank if workerRootVolumeType is not io1
#workerRootVolumeIOPS: 0

# Tenancy of the worker nodes. Options are "default" and "dedicated"
# Documentation: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html
# workerTenancy: default

# Price (Dollars) to bid for spot instances. Omit for on-demand instances.
# workerSpotPrice: "0.05"

# Existing "glue" security groups attached to worker nodes which are typically used to allow access from worker nodes to services running on an existing infrastructure
# workerSecurityGroupIds:
#   - sg-1234abcd
#   - sg-5678efab

## Etcd Cluster config
## WARNING: Any changes to etcd parameters after the cluster is first created will not be applied
## during a cluster upgrade, due to concerns over data loss.
## This situation is being rectified with work towards automated management of etcd clusters

# Number of etcd nodes
# (Set to an odd number >= 3 for HA control plane)
# etcdCount: 1

#etcd:
#  subnets:
#    - availabilityZone: us-west-1a
#      instanceCIDR: "10.0.2.0/24"
#    - availabilityZone: us-west-1b
#      instanceCIDR: "10.0.3.0/24"

# Instance type for etcd node
# etcdInstanceType: t2.medium

# Root volume size (GiB) for etcd node
# etcdRootVolumeSize: 30

# Root volume type for etcd node (one of standard, io1, or gp2)
# etcdRootVolumeType: gp2

# Number of I/O operations per second (IOPS) that the etcd node's root volume supports. Leave blank if etcdRootVolumeType is not io1
# etcdRootVolumeIOPS: 0

# Use ephemeral instance storage for etcd data volume instead of EBS?
# (Recommended set to true for high-throughput control planes)
# etcdDataVolumeEphemeral: false

# Data volume size (GiB) for etcd node
# if etcdDataVolumeEphemeral=true, this value is ignored. The size of ephemeral volumes is not configurable.
# etcdDataVolumeSize: 30

# Data volume type for etcd node (one of standard, io1, or gp2)
# etcdDataVolumeType: gp2

# Number of I/O operations per second (IOPS) that the etcd node's data volume supports. Leave blank if etcdDataVolumeType is not io1
# etcdDataVolumeIOPS: 0

# Tenancy of the etcd instances. Options are "default" and "dedicated"
# Documentation: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html
# etcdTenancy: default

## Networking config

# ID of existing VPC to create subnet in. Leave blank to create a new VPC
# vpcId:

# ID of existing Internet Gateway to associate subnet with. Leave blank to create a new Internet Gateway
# internetGatewayId:

# ID of existing route table in existing VPC to attach subnet to. Leave blank to use the VPC's main route table.
# routeTableId:

# CIDR for Kubernetes VPC. If vpcId is specified, must match the CIDR of existing vpc.
# vpcCIDR: "10.0.0.0/16"

# CIDR for Kubernetes subnet when placing nodes in a single availability zone (not highly-available) Leave commented out for multi availability zone setting and use the below `subnets` section instead.
# instanceCIDR: "10.0.0.0/24"

# Kubernetes subnets with their CIDRs and availability zones. Differentiating availability zone for 2 or more subnets result in high-availability (failures of a single availability zone won't result in immediate downtimes)
# subnets:
#   - availabilityZone: us-west-1a
#     instanceCIDR: "10.0.0.0/24"
#   - availabilityZone: us-west-1b
#     instanceCIDR: "10.0.1.0/24"
#     # natGateway:
#     #   # Pre-allocated NAT Gateway. Used with private subnets.
#     #   id: "ngw-abcdef12"
#     #   # Pre-allocated EIP for NAT Gateways. Used with private subnets.
#     #   eipAllocationId: "eipalloc-abcdef12"

# CIDR for all service IP addresses
# serviceCIDR: "10.3.0.0/24"

# CIDR for all pod IP addresses
# podCIDR: "10.2.0.0/16"

# IP address of Kubernetes dns service (must be contained by serviceCIDR)
# dnsServiceIP: 10.3.0.10

# Uncomment to provision nodes without a public IP. This assumes your VPC route table is setup to route to the internet via a NAT gateway.
# If you did not set vpcId and routeTableId the cluster will not bootstrap.
# mapPublicIPs: false

# Expiration in days from creation time of TLS assets. By default, the CA will
# expire in 10 years and the server and client certificates will expire in 1
# year.
#tlsCADurationDays: 3650
#tlsCertDurationDays: 365

# Version of hyperkube image to use. This is the tag for the hyperkube image repository.
# kubernetesVersion: v1.5.2_coreos.0

# Hyperkube image repository to use.
# hyperkubeImageRepo: quay.io/coreos/hyperkube

# AWS CLI image repository to use.
# awsCliImageRepo: quay.io/coreos/awscli

# AWS CLI image tag to use.
# awsCliTag: master

# Use Calico for network policy.
# useCalico: false

# Create MountTargets for a pre-existing Elastic File System (Amazon EFS). Enter the resource id, eg "fs-47a2c22e"
# This is a NFS share that will be available across the entire cluster through a hostPath volume on the "/efs" mountpoint
#
# You can create a new EFS volume using the CLI:
# $ aws efs create-file-system --creation-token $(uuidgen)
#
# Beware that an EFS file system can not be mounted from mutiple subnets from the same availability zone and
# therefore this feature won't work like you might have expected when you're deploying your cluster to an existing VPC and
# wanted to mount an existing EFS to the subnet(s) created by kube-aws
# See https://github.com/coreos/kube-aws/issues/208 for more information
#elasticFileSystemId: fs-47a2c22e

# Determines the container runtime for kubernetes to use. Accepts 'docker' or 'rkt'.
# containerRuntime: docker

# If you do not want kube-aws to manage certificaes, set it to false. If you do that
# you are responsible for making sure that nodes have correct certificates by the time
# daemons start up.
# manageCertificates: true

# Experimental features will change in backward-incompatible ways
# experimental:
#   # Used to provide `/etc/environment` env vars with values from arbitrary CloudFormation refs
#   awsEnvironment:
#     enabled: true
#     environment:
#       CFNSTACK: '{ "Ref" : "AWS::StackId" }'
#   # Enable audit log for apiserver. Recommended when `rbac` is enabled.
#   auditLog:
#     enabled: true
#     maxage: 30
#     logpath: /dev/stdout
#   # Add predefined set of labels to the nodes
#   # The set includes names of launch configurations and autoscaling groups
#   awsNodeLabels:
#     enabled: true
#   # This option has not yet been tested with rkt as container runtime
#   ephemeralImageStorage:
#     enabled: true
#   # Configuration for external managed ELBs for worker nodes
#   loadBalancer:
#     enabled: true
#     # Names of ELBs attached to worker nodes
#     names: [ "manuallymanagedelb" ]
#     # IDs of "glue" security groups attached to worker nodes to allow the ELBs to communicate with worker nodes
#     securityGroupIds: [ "sg-87654321" ]
#   nodeDrainer:
#     enabled: true
#   nodeLabels:
#     kube-aws.coreos.com/role: worker
#   taints:
#     - key: dedicated
#       value: search
#       effect: NoSchedule
#   # When enabled, autoscaling groups managing worker and controller nodes wait for nodes to be up and running.
#   # Although this is still an experimental feature, it is recommended to be enabled and
#   # it will even be enabled by default in the near future.
#   waitSignal:
#     enabled: true
#   plugins:
#     # When enabled, you also need to configure a minimum set of role bindings or everything breaks.
#     # See https://github.com/coreos/kube-aws/issues/230 for more information.
#     rbac:
#       enabled: true

# AWS Tags for cloudformation stack resources
#stackTags:
#  Name: "Kubernetes"
#  Environment: "Production"

# User-provided YAML map available in stack-template.json
#customSettings:
#  key1: [ 1, 2, 3 ]
